src/Admin/Models/OrganizationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bit.Core.Entities;
using Bit.Core.Enums;
using Bit.Core.Models.Data;

namespace Bit.Admin.Models
{
    public class OrganizationViewModel
    {
        public OrganizationViewModel() { }

        public OrganizationViewModel(Organization org, IEnumerable<OrganizationUserUserDetails> orgUsers,
            IEnumerable<Cipher> ciphers, IEnumerable<Collection> collections, IEnumerable<Group> groups,
            IEnumerable<Policy> policies)
        {
            Organization = org;
            HasPublicPrivateKeys = org.PublicKey != null && org.PrivateKey != null;
            UserInvitedCount = orgUsers.Count(u => u.Status == OrganizationUserStatusType.Invited);
            UserAcceptedCount = orgUsers.Count(u => u.Status == OrganizationUserStatusType.Accepted);
            UserConfirmedCount = orgUsers.Count(u => u.Status == OrganizationUserStatusType.Confirmed);
            UserCount = orgUsers.Count();
            CipherCount = ciphers.Count();
            CollectionCount = collections.Count();
            GroupCount = groups?.Count() ?? 0;
            PolicyCount = policies?.Count() ?? 0;
            Owners = string.Join(", ",
                orgUsers
                .Where(u => u.Type == OrganizationUserType.Owner && u.Status == OrganizationUserStatusType.Confirmed)
                .Select(u => u.Email));
            Admins = string.Join(", ",
                orgUsers
                .Where(u => u.Type == OrganizationUserType.Admin && u.Status == OrganizationUserStatusType.Confirmed)
                .Select(u => u.Email));
        }

        public Organization Organization { get; set; }
        public string Owners { get; set; }
        public string Admins { get; set; }
        public int UserInvitedCount { get; set; }
        public int UserConfirmedCount { get; set; }
        public int UserAcceptedCount { get; set; }
        public int UserCount { get; set; }
        public int CipherCount { get; set; }
        public int CollectionCount { get; set; }
        public int GroupCount { get; set; }
        public int PolicyCount { get; set; }
        public bool HasPublicPrivateKeys { get; set; }
    }
}

src/Admin/Models/ProviderViewModel.cs
using System.Collections.Generic;
using System.Linq;
using Bit.Core.Entities.Provider;
using Bit.Core.Enums.Provider;
using Bit.Core.Models.Data;

namespace Bit.Admin.Models
{
    public class ProviderViewModel
    {
        public ProviderViewModel() { }

        public ProviderViewModel(Provider provider, IEnumerable<ProviderUserUserDetails> providerUsers, IEnumerable<ProviderOrganizationOrganizationDetails> organizations)
        {
            Provider = provider;
            UserCount = providerUsers.Count();
            ProviderAdmins = providerUsers.Where(u => u.Type == ProviderUserType.ProviderAdmin);

            ProviderOrganizations = organizations.Where(o => o.ProviderId == provider.Id);
        }

        public int UserCount { get; set; }
        public Provider Provider { get; set; }
        public IEnumerable<ProviderUserUserDetails> ProviderAdmins { get; set; }
        public IEnumerable<ProviderOrganizationOrganizationDetails> ProviderOrganizations { get; set; }
    }
}

src/Admin/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Bit.Admin.Models;
using Bit.Core.Entities;
using Bit.Core.Enums;
using Bit.Core.Models.Business;
using Bit.Core.Repositories;
using Bit.Core.Services;
using Bit.Core.Settings;
using Bit.Core.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bit.Admin.Controllers
{
    [Authorize]
    public class OrganizationsController : Controller
    {
        private readonly IOrganizationRepository _organizationRepository;
        private readonly IOrganizationUserRepository _organizationUserRepository;
        private readonly ICipherRepository _cipherRepository;
        private readonly ICollectionRepository _collectionRepository;
        private readonly IGroupRepository _groupRepository;
        private readonly IPolicyRepository _policyRepository;
        private readonly IPaymentService _paymentService;
        private readonly IApplicationCacheService _applicationCacheService;
        private readonly GlobalSettings _globalSettings;
        private readonly IReferenceEventService _referenceEventService;
        private readonly IUserService _userService;

        public OrganizationsController(
            IOrganizationRepository organizationRepository,
            IOrganizationUserRepository organizationUserRepository,
            ICipherRepository cipherRepository,
            ICollectionRepository collectionRepository,
            IGroupRepository groupRepository,
            IPolicyRepository policyRepository,
            IPaymentService paymentService,
            IApplicationCacheService applicationCacheService,
            GlobalSettings globalSettings,
            IReferenceEventService referenceEventService,
            IUserService userService)
        {
            _organizationRepository = organizationRepository;
            _organizationUserRepository = organizationUserRepository;
            _cipherRepository = cipherRepository;
            _collectionRepository = collectionRepository;
            _groupRepository = groupRepository;
            _policyRepository = policyRepository;
            _paymentService = paymentService;
            _applicationCacheService = applicationCacheService;
            _globalSettings = globalSettings;
            _referenceEventService = referenceEventService;
            _userService = userService;
        }

        public async Task<IActionResult> Index(string name = null, string userEmail = null, bool? paid = null,
            int page = 1, int count = 25)
        {
            if (page < 1)
            {
                page = 1;
            }

            if (count < 1)
            {
                count = 1;
            }

            var skip = (page - 1) * count;
            var organizations = await _organizationRepository.SearchAsync(name, userEmail, paid, skip, count);
            return View(new OrganizationsModel
            {
                Items = organizations as List<Organization>,
                Name = string.IsNullOrWhiteSpace(name) ? null : name,
                UserEmail = string.IsNullOrWhiteSpace(userEmail) ? null : userEmail,
                Paid = paid,
                Page = page,
                Count = count,
                Action = _globalSettings.SelfHosted ? "View" : "Edit",
                SelfHosted = _globalSettings.SelfHosted
            });
        }

        public async Task<IActionResult> View(Guid id)
        {
            var organization = await _organizationRepository.GetByIdAsync(id);
            if (organization == null)
            {
                return RedirectToAction("Index");
            }

            var ciphers = await _cipherRepository.GetManyByOrganizationIdAsync(id);
            var collections = await _collectionRepository.GetManyByOrganizationIdAsync(id);
            IEnumerable<Group> groups = null;
            if (organization.UseGroups)
            {
                groups = await _groupRepository.GetManyByOrganizationIdAsync(id);
            }
            IEnumerable<Policy> policies = null;
            if (organization.UsePolicies)
            {
                policies = await _policyRepository.GetManyByOrganizationIdAsync(id);
            }
            var users = await _organizationUserRepository.GetManyDetailsByOrganizationAsync(id);
            return View(new OrganizationViewModel(organization, users, ciphers, collections, groups, policies));
        }

        [SelfHosted(NotSelfHostedOnly = true)]
        public async Task<IActionResult> Edit(Guid id)
        {
            var organization = await _organizationRepository.GetByIdAsync(id);
            if (organization == null)
            {
                return RedirectToAction("Index");
            }

            var ciphers = await _cipherRepository.GetManyByOrganizationIdAsync(id);
            var collections = await _collectionRepository.GetManyByOrganizationIdAsync(id);
            IEnumerable<Group> groups = null;
            if (organization.UseGroups)
            {
                groups = await _groupRepository.GetManyByOrganizationIdAsync(id);
            }
            IEnumerable<Policy> policies = null;
            if (organization.UsePolicies)
            {
                policies = await _policyRepository.GetManyByOrganizationIdAsync(id);
            }
            var users = await _organizationUserRepository.GetManyDetailsByOrganizationAsync(id);
            var billingInfo = await _paymentService.GetBillingAsync(organization);
            return View(new OrganizationEditModel(organization, users, ciphers, collections, groups, policies,
                billingInfo, _globalSettings));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SelfHosted(NotSelfHostedOnly = true)]
        public async Task<IActionResult> Edit(Guid id, OrganizationEditModel model)
        {
            var organization = await _organizationRepository.GetByIdAsync(id);
            model.ToOrganization(organization);
            await _organizationRepository.ReplaceAsync(organization);
            await _applicationCacheService.UpsertOrganizationAbilityAsync(organization);
            await _referenceEventService.RaiseEventAsync(new ReferenceEvent(ReferenceEventType.OrganizationEditedByAdmin, organization)
            {
                EventRaisedByUser = _userService.GetUserName(User),
                SalesAssistedTrialStarted = model.SalesAssistedTrialStarted,
            });
            return RedirectToAction("Edit", new { id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {
            var organization = await _organizationRepository.GetByIdAsync(id);
            if (organization != null)
            {
                await _organizationRepository.DeleteAsync(organization);
                await _applicationCacheService.DeleteOrganizationAbilityAsync(organization.Id);
            }

            return RedirectToAction("Index");
        }
    }
}

src/Admin/Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Bit.Admin.Models;
using Bit.Core.Entities.Provider;
using Bit.Core.Repositories;
using Bit.Core.Services;
using Bit.Core.Settings;
using Bit.Core.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bit.Admin.Controllers
{
    [Authorize]
    [SelfHosted(NotSelfHostedOnly = true)]
    public class ProvidersController : Controller
    {
        private readonly IProviderRepository _providerRepository;
        private readonly IProviderUserRepository _providerUserRepository;
        private readonly IProviderOrganizationRepository _providerOrganizationRepository;
        private readonly GlobalSettings _globalSettings;
        private readonly IApplicationCacheService _applicationCacheService;
        private readonly IProviderService _providerService;

        public ProvidersController(IProviderRepository providerRepository, IProviderUserRepository providerUserRepository,
            IProviderOrganizationRepository providerOrganizationRepository, IProviderService providerService,
            GlobalSettings globalSettings, IApplicationCacheService applicationCacheService)
        {
            _providerRepository = providerRepository;
            _providerUserRepository = providerUserRepository;
            _providerOrganizationRepository = providerOrganizationRepository;
            _providerService = providerService;
            _globalSettings = globalSettings;
            _applicationCacheService = applicationCacheService;
        }

        public async Task<IActionResult> Index(string name = null, string userEmail = null, int page = 1, int count = 25)
        {
            if (page < 1)
            {
                page = 1;
            }

            if (count < 1)
            {
                count = 1;
            }

            var skip = (page - 1) * count;
            var providers = await _providerRepository.SearchAsync(name, userEmail, skip, count);
            return View(new ProvidersModel
            {
                Items = providers as List<Provider>,
                Name = string.IsNullOrWhiteSpace(name) ? null : name,
                UserEmail = string.IsNullOrWhiteSpace(userEmail) ? null : userEmail,
                Page = page,
                Count = count,
                Action = _globalSettings.SelfHosted ? "View" : "Edit",
                SelfHosted = _globalSettings.SelfHosted
            });
        }

        public IActionResult Create(string ownerEmail = null)
        {
            return View(new CreateProviderModel
            {
                OwnerEmail = ownerEmail
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProviderModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await _providerService.CreateAsync(model.OwnerEmail);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> View(Guid id)
        {
            var provider = await _providerRepository.GetByIdAsync(id);
            if (provider == null)
            {
                return RedirectToAction("Index");
            }

            var users = await _providerUserRepository.GetManyDetailsByProviderAsync(id);
            var providerOrganizations = await _providerOrganizationRepository.GetManyDetailsByProviderAsync(id);
            return View(new ProviderViewModel(provider, users, providerOrganizations));
        }

        [SelfHosted(NotSelfHostedOnly = true)]
        public async Task<IActionResult> Edit(Guid id)
        {
            var provider = await _providerRepository.GetByIdAsync(id);
            if (provider == null)
            {
                return RedirectToAction("Index");
            }

            var users = await _providerUserRepository.GetManyDetailsByProviderAsync(id);
            var providerOrganizations = await _providerOrganizationRepository.GetManyDetailsByProviderAsync(id);
            return View(new ProviderEditModel(provider, users, providerOrganizations));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SelfHosted(NotSelfHostedOnly = true)]
        public async Task<IActionResult> Edit(Guid id, ProviderEditModel model)
        {
            var provider = await _providerRepository.GetByIdAsync(id);
            if (provider == null)
            {
                return RedirectToAction("Index");
            }

            model.ToProvider(provider);
            await _providerRepository.ReplaceAsync(provider);
            await _applicationCacheService.UpsertProviderAbilityAsync(provider);
            return RedirectToAction("Edit", new { id });
        }

        public async Task<IActionResult> ResendInvite(Guid ownerId, Guid providerId)
        {
            await _providerService.ResendProviderSetupInviteEmailAsync(providerId, ownerId);
            TempData["InviteResentTo"] = ownerId;
            return RedirectToAction("Edit", new { id = providerId });
        }
    }
}

src/Admin/Views/Providers/Admins.cshtml
@model ProviderViewModel
<h2>Provider Admins</h2>
<div class="row">
    <div class="col-8">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th style="width: 190px;">Email</th>
                        <th style="width: 40px;">Status</th>
                        <th style="width: 30px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @if(!Model.ProviderAdmins.Any())
                    {
                        <tr>
                            <td colspan="6">No results to list.</td>
                        </tr>
                    }
                    else
                    {
                        @foreach(var admin in Model.ProviderAdmins)
                        {
                            <tr>
                                <td class="align-middle">
                                    @admin.Email
                                </td>
                                <td class="align-middle">
                                    @admin.Status
                                </td>
                                <td>
                                    @if(admin.Status.Equals(ProviderUserStatusType.Confirmed) 
                                        && @Model.Provider.Status.Equals(ProviderStatusType.Pending))
                                    {
                                        @if(@TempData["InviteResentTo"] != null && @TempData["InviteResentTo"].ToString() == @admin.UserId.Value.ToString())
                                        {
                                            <button class="btn btn-outline-success btn-sm disabled" disabled>Invite Resent!</button>
                                        }
                                        else
                                        {
                                            <a class="btn btn-outline-secondary btn-sm" 
                                                data-id="@admin.Id" asp-controller="Providers" 
                                                asp-action="ResendInvite" asp-route-ownerId="@admin.UserId" 
                                                asp-route-providerId="@Model.Provider.Id">
                                                Resend Setup Invite
                                            </a>
                                        }
                                    }
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

src/Admin/Views/Providers/Create.cshtml
@model CreateProviderModel
@{
    ViewData["Title"] = "Create Provider";
}

<h1>Create Provider</h1>

<form method="post">
    <div asp-validation-summary="All" class="alert alert-danger"></div>
    
    <div class="form-group">
        <label asp-for="OwnerEmail"></label>
        <input type="text" class="form-control" asp-for="OwnerEmail">
    </div>
    
    <button type="submit" class="btn btn-primary mb-2">Create Provider</button>
</form>

src/Admin/Views/Providers/Edit.cshtml
@model ProviderEditModel
@{
    ViewData["Title"] = "Provider: " + Model.Provider.Name;
}

<h1>Provider <small>@Model.Provider.Name</small></h1>

<h2>Provider Information</h2>
@await Html.PartialAsync("_ViewInformation", Model)
@await Html.PartialAsync("Admins", Model)
<form method="post" id="edit-form">
    <h2>General</h2>
    <div class="row">
        <div class="col-sm">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input type="text" class="form-control" asp-for="Name" required>
            </div>
        </div>
    </div>
    <h2>Business Information</h2>
    <div class="row">
        <div class="col-sm">
            <div class="form-group">
                <label asp-for="BusinessName"></label>
                <input type="text" class="form-control" asp-for="BusinessName">
            </div>
        </div>
    </div>
    <h2>Billing</h2>
    <div class="row">
        <div class="col-sm">
            <div class="form-group">
                <label asp-for="BillingEmail"></label>
                <input type="email" class="form-control" asp-for="BillingEmail">
            </div>
        </div>
    </div>
</form>
@await Html.PartialAsync("Organizations", Model)
<div class="d-flex mt-4">
    <button type="submit" class="btn btn-primary" form="edit-form">Save</button>
</div>

src/Admin/Views/Providers/Index.cshtml
@model ProvidersModel
@{
    ViewData["Title"] = "Providers";
}

<h1>Providers</h1>

<div class="row mb-2">
    <div class="col">
        <form class="form-inline mb-2" method="get">
            <label class="sr-only" asp-for="Name">Name</label>
            <input type="text" class="form-control mb-2 mr-2" placeholder="Name" asp-for="Name" name="name">
            <label class="sr-only" asp-for="UserEmail">User email</label>
            <input type="text" class="form-control mb-2 mr-2" placeholder="User email" asp-for="UserEmail" name="userEmail">
            <button type="submit" class="btn btn-primary mb-2" title="Search"><i class="fa fa-search"></i> Search</button>
        </form>
    </div>
    <div class="col-auto">
        <a asp-action="Create" class="btn btn-secondary">Create Provider</a>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th style="width: 190px;">Status</th>
                <th style="width: 150px;">Created</th>
            </tr>
        </thead>
        <tbody>
            @if(!Model.Items.Any())
            {
                <tr>
                    <td colspan="5">No results to list.</td>
                </tr>
            }
            else
            {
                @foreach(var provider in Model.Items)
                {
                    <tr>
                        <td>
                            <a asp-action="@Model.Action" asp-route-id="@provider.Id">@(provider.Name ?? "Pending")</a>
                        </td>
                        <td>@provider.Status</td>
                        <td>
                            <span title="@provider.CreationDate.ToString()">
                                @provider.CreationDate.ToShortDateString()
                            </span>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<nav>
    <ul class="pagination">
        @if(Model.PreviousPage.HasValue)
        {
            <li class="page-item">
                <a class="page-link" asp-action="Index" asp-route-page="@Model.PreviousPage.Value"
                   asp-route-count="@Model.Count" asp-route-userEmail="@Model.UserEmail"
                   asp-route-name="@Model.Name" asp-route-paid="@Model.Paid">Previous</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
        }
        @if(Model.NextPage.HasValue)
        {
            <li class="page-item">
                <a class="page-link" asp-action="Index" asp-route-page="@Model.NextPage.Value"
                   asp-route-count="@Model.Count" asp-route-userEmail="@Model.UserEmail"
                   asp-route-name="@Model.Name" asp-route-paid="@Model.Paid">Next</a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Next</a>
            </li>
        }
    </ul>
</nav>

src/Admin/Views/Providers/Organizations.cshtml
@model ProviderViewModel
<h2>Provider Organizations</h2>
<div class="row">
    <div class="col-sm">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Name</th>
                    </tr>
                </thead>
                <tbody>
                    @if (!Model.ProviderOrganizations.Any())
                    {
                        <tr>
                            <td colspan="6">No results to list.</td>
                        </tr>
                    }
                    else
                    {
                        @foreach (var org in Model.ProviderOrganizations)
                        {
                            <tr>
                                <td class="align-middle">
                                    <a asp-controller="Organizations" asp-action="Edit"
                                asp-route-id="@org.OrganizationId">@org.OrganizationName</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

src/Admin/Views/Providers/View.cshtml
@model ProviderViewModel
@{
    ViewData["Title"] = "Provider: " + Model.Provider.Name;
}

<h1>Provider <small>@Model.Provider.Name</small></h1>

<h2>Information</h2>
@await Html.PartialAsync("_ViewInformation", Model)
@await Html.PartialAsync("Admins", Model)
@await Html.PartialAsync("Organizations", Model)

src/Admin/Views/Providers/_ViewInformation.cshtml
@model ProviderViewModel
<dl class="row">
    <dt class="col-sm-4 col-lg-3">Id</dt>
    <dd class="col-sm-8 col-lg-9"><code>@Model.Provider.Id</code></dd>

    <dt class="col-sm-4 col-lg-3">Status</dt>
    <dd class="col-sm-8 col-lg-9">@Model.Provider.Status</dd>
    
    <dt class="col-sm-4 col-lg-3">Users</dt>
    <dd class="col-sm-8 col-lg-9">@Model.UserCount</dd>
    
    <dt class="col-sm-4 col-lg-3">Created</dt>
    <dd class="col-sm-8 col-lg-9">@Model.Provider.CreationDate.ToString()</dd>

    <dt class="col-sm-4 col-lg-3">Modified</dt>
    <dd class="col-sm-8 col-lg-9">@Model.Provider.RevisionDate.ToString()</dd>
</dl>